### ISSUE TITLE
Couldn't train

### ISSUE THREAD

**Issue by ReijiSoftmaxSaito** [ByeongHyunPak/tqdm#4]
I attempted to perform training using `bash dist_train.sh configs/tqdm/tqdm_eva_vit-l_1e-5_20k-g2c-512.py 2`, but I encountered the following error and could not resolve it. Could you please help me?
![problem](https://github.com/user-attachments/assets/f5448ea5-e051-451f-98a0-8ecda8c61d33)

**Comment by ByeongHyunPak** [comment]
Did you run the following code?
Please refer [TLDR repo](https://github.com/ssssshwan/TLDR/tree/main?tab=readme-ov-file#setup-datasets).
```
python tools/convert_datasets/gta.py data/gta --nproc 8
python tools/convert_datasets/cityscapes.py data/cityscapes --nproc 8
```

**Comment by ReijiSoftmaxSaito** [comment]
I fixed it, thank you! The issue was that I was using `gta.py` from TLDR...
